### ISSUE TITLE
Cancel previous in-progress actions on branch, tag or PR when new code is pushed

### ISSUE THREAD

**Issue by jdkanani** [0xmozak/mozak-vm#232]
Add the following code to the workflow

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
```
