### ISSUE TITLE
Investigate AVX bug

### ISSUE THREAD

**Issue by matthiasgoergens** [0xmozak/mozak-vm#756]
Running tests with the following in my `~/.cargo/config.toml` fails:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]
```

Error message is:
```
thread 'cpu::add::tests::prove_add_mozak_example' panicked at circuits/src/stark/poly.rs:87:42:
range end index 4 out of range for slice of length 2
```

In plonky2 we have 3 different implementations of `compute_quotient_polys`.  I think some of them know how to deal with this:

```
~/m/p/plonky2 (main)$ git grep 'fn compute_quotient_polys'
evm/src/prover.rs:fn compute_quotient_polys<'a, F, P, C, S, const D: usize>(
plonky2/src/plonk/prover.rs:fn compute_quotient_polys<
starky/src/prover.rs:fn compute_quotient_polys<'a, F, P, C, S, const D: usize>(
```
